name: clang-format check
run-name: clang-format check

on:
  pull_request:
    paths-ignore:
    - README.md
    - 'docs/**'
    types: [ opened, reopened, synchronize ]

permissions: read-all

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        clangFormatVersion: 14